/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ddbc2bd7-9c89-4678-aa71-e0cb08a053d2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_3eZPmB9IO",
    "aws_user_pools_web_client_id": "6ai7332nlfb0p7scd1h9rjobnc",
    "oauth": {}
};


export default awsmobile;
